### ISSUE TITLE
each lobby (or game) has its own chat

### ISSUE THREAD

**Issue by Stud-FH** [sopra-fs21-group-4/client#66]
- [x] when a new game is created, a new chat is created automatically. This chat is owned by the new game. 
- [x] in the front-end, the game-chat is displayed in parallel to the actual game UI.
- [x] both the chat and the game are updated in parallel.

**Comment by Max-Zurbriggen** [comment]
Commit:
1082a3d14b174b49e5af407147ecbb46a924f79c
78b35c401abb2e13d7dff703ee579d10f3822c44
